# JWT Ayarları
jwt:
  secret-key: a2V5LXBhc3N3b3JkLWZvci1zZWN1cmUtand0LWFwcGxpY2F0aW9uLXNwcmluZy1ib290
  expiration: 86400000 # 24 Saat (Milisaniye cinsinden)

# Frontend Yönlendirme URL'i
app:
  frontend:
    url: http://localhost:4200

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: SIZIN_GOOGLE_CLIENT_ID_BILGINIZ
            client-secret: SIZIN_GOOGLE_CLIENT_SECRET_BILGINIZ
            scope:
              - email
              - profile

  # PostgreSQL ve PostGIS (GIS) Yapılandırması
  datasource:
    url: jdbc:postgresql://localhost:5432/patimati_db
    username: postgres
    password: postgres_sifre
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # PostGIS Dialect
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect