name: CI Pipeline

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # GitHub Actions ortamına PostGIS yüklü veritabanı servisi ekliyoruz
    services:
      postgres:
        image: postgis/postgis:15-3.4-alpine
        env:
          POSTGRES_DB: patimati_db
          POSTGRES_USER: ${{ vars.DB_USER }}       # GitHub Variables üzerinden güvenli çekilir
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}   # GitHub Secrets üzerinden şifreli çekilir
        ports:
          - 5432:5432
        # Veritabanının tamamen ayağa kalkmasını beklemek için sağlık kontrolü
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      rabbitmq:
        image: rabbitmq:3.13-management-alpine
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Repoyu Klonla
        uses: actions/checkout@v4

      - name: Java JDK 21 Kurulumu
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Maven ile Derle ve Doğrula
        # Spring Boot testlerinin bu oluşturduğumuz veritabanına bağlanabilmesi için env değişkenleri ekliyoruz
        run: mvn clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/patimati_db
          SPRING_DATASOURCE_USERNAME: ${{ vars.DB_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}